"""create_audit_tables

Revision ID: 9cc40d9ae48d
Revises: a8f43f622eab
Create Date: 2026-07-12 14:10:31.443570
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc40d9ae48d'
down_revision: Union[str, None] = 'a8f43f622eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_cycles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.Enum('ALL', 'DEPARTMENT', 'LOCATION', name='auditscopetype', create_constraint=True), server_default='ALL', nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='auditcyclestatus', create_constraint=True), server_default='OPEN', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_cycles_id'), 'audit_cycles', ['id'], unique=False)
    op.create_table('audit_auditors',
    sa.Column('audit_cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_cycle_id', 'user_id'),
    sa.UniqueConstraint('audit_cycle_id', 'user_id', name='uq_audit_auditors')
    )
    op.create_table('audit_records',
    sa.Column('audit_cycle_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'MISSING', 'DAMAGED', name='verificationstatus', create_constraint=True), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_cycle_id', 'asset_id', name='uq_audit_records_cycle_asset')
    )
    op.create_index(op.f('ix_audit_records_asset_id'), 'audit_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_audit_records_audit_cycle_id'), 'audit_records', ['audit_cycle_id'], unique=False)
    op.create_index(op.f('ix_audit_records_id'), 'audit_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_records_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_audit_cycle_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_asset_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_table('audit_auditors')
    op.drop_index(op.f('ix_audit_cycles_id'), table_name='audit_cycles')
    op.drop_table('audit_cycles')
    # ### end Alembic commands ###
