"""create_resource_bookings

Revision ID: bdd676870c1e
Revises: 82487db833de
Create Date: 2026-07-12 12:25:30.087893
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd676870c1e'
down_revision: Union[str, None] = '82487db833de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_bookings',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='bookingstatus', create_constraint=True), server_default='UPCOMING', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_bookings_asset_id'), 'resource_bookings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_resource_bookings_department_id'), 'resource_bookings', ['department_id'], unique=False)
    op.create_index(op.f('ix_resource_bookings_employee_id'), 'resource_bookings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_resource_bookings_end_datetime'), 'resource_bookings', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_resource_bookings_id'), 'resource_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_resource_bookings_start_datetime'), 'resource_bookings', ['start_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_bookings_start_datetime'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_id'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_end_datetime'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_employee_id'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_department_id'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_asset_id'), table_name='resource_bookings')
    op.drop_table('resource_bookings')
    # ### end Alembic commands ###
