"""create_allocations_transfers

Revision ID: 82487db833de
Revises: 4d7aa56f1fd4
Create Date: 2026-07-12 11:25:23.211944
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82487db833de'
down_revision: Union[str, None] = '4d7aa56f1fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_allocations',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allocated_by', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='allocationstatus', create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_allocations_asset_id'), 'asset_allocations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_allocations_employee_id'), 'asset_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_asset_allocations_id'), 'asset_allocations', ['id'], unique=False)
    op.create_table('transfer_requests',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('from_employee_id', sa.Integer(), nullable=False),
    sa.Column('to_employee_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='transferstatus', create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_requests_asset_id'), 'transfer_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_id'), 'transfer_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_requests_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_asset_id'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    op.drop_index(op.f('ix_asset_allocations_id'), table_name='asset_allocations')
    op.drop_index(op.f('ix_asset_allocations_employee_id'), table_name='asset_allocations')
    op.drop_index(op.f('ix_asset_allocations_asset_id'), table_name='asset_allocations')
    op.drop_table('asset_allocations')
    # ### end Alembic commands ###
